name: pyci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: .
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
